# config/tinymce.yml
default:
  height: 500
  width: '100%'
  plugins:
    - advlist
    - autolink
    - lists
    - link
    - image
    - charmap
    - preview
    - anchor
    - searchreplace
    - visualblocks
    - code
    - fullscreen
    - insertdatetime
    - media
    - table
    - paste
    - code
    - help
    - wordcount
  toolbar:
    - "undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image | fullscreen"
  menubar: false
  statusbar: false
  # content_css:
  #   - "/stylesheets/content.css"
